### ISSUE TITLE
LWP isn't following redirect?

### ISSUE THREAD

**Issue by cPMarco** [teodesian/TestRail-Perl#111] opened 2016-10-25 22:07 UTC
```
$ grep url ~/.testrailrc 
apiurl=http://testrail.domain.net
```

```
$ prove 01-check_access_ip_endpoint.t -m -PTestRail="spawn=73,run=00 Tickets Master Daily,version=one,sections=API"
# PROCESSING RESULTS FROM TEST FILE: 01-check_access_ip_endpoint.t
01-check_access_ip_endpoint.t .. 1/2 # Setting results...
# Test elapsed: 0m 1s
# Attempting to find case by title '01-check_access_ip_endpoint.t in run 16132'...
# Reporting result of case 26870622 in run 16132 as status '1'...ERROR: Arguments Bad: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://testrail.domain.net/index.php?/api/v2/add_result/26870622">here</a>.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at testrail.domain.net Port 80</address>
</body></html>
 at /Users/username/perl5/lib/perl5/TestRail/API.pm line 159.
    TestRail::API::_doRequest('TestRail::API=HASH(0x7fe2ee9be260)', 'index.php?/api/v2/add_result/26870622', 'POST', 'HASH(0x7fe2eed87700)') called at /Users/username/perl5/lib/perl5/TestRail/API.pm line 1128
    TestRail::API::createTestResults('TestRail::API=HASH(0x7fe2ee9be260)', 26870622, 1, '[16:53:31 Oct 25 2016 (0s)] ok 1 - An object of class \'Idev:...', 'HASH(0x7fe2ee1f4528)', 'HASH(0x7fe2eed81f30)') called at /Users/username/perl5/lib/perl5/Test/Rail/Parser.pm line 626
    Test::Rail::Parser::_set_result('Test::Rail::Parser=HASH(0x7fe2ec692430)', 16132, '01-check_access_ip_endpoint.t', 1, '[16:53:31 Oct 25 2016 (0s)] ok 1 - An object of class \'Idev:...', 'HASH(0x7fe2ee1f4528)', 'HASH(0x7fe2eed81f30)') called at /Users/username/perl5/lib/perl5/Test/Rail/Parser.pm line 586
    Test::Rail::Parser::EOFCallback('Test::Rail::Parser=HASH(0x7fe2ec692430)') called at /Users/username/perl5/lib/perl5/TAP/Base.pm line 105
    TAP::Base::_make_callback('Test::Rail::Parser=HASH(0x7fe2ec692430)', 'EOF', 'Test::Rail::Parser=HASH(0x7fe2ec692430)') called at /Users/username/perl5/lib/perl5/TAP/Parser.pm line 1450
    TAP::Parser::__ANON__() called at /Users/username/perl5/lib/perl5/TAP/Parser.pm line 315
    TAP::Parser::next('Test::Rail::Parser=HASH(0x7fe2ec692430)') called at /Users/username/perl5/lib/perl5/TAP/Harness.pm line 653
    TAP::Harness::_aggregate_single('Test::Rail::Harness=HASH(0x7fe2ecfd98d0)', 'TAP::Parser::Aggregator=HASH(0x7fe2ecf95ea0)', 'TAP::Parser::Scheduler=HASH(0x7fe2ee16e878)') called at /Users/username/perl5/lib/perl5/TAP/Harness.pm line 743
    TAP::Harness::aggregate_tests('Test::Rail::Harness=HASH(0x7fe2ecfd98d0)', 'TAP::Parser::Aggregator=HASH(0x7fe2ecf95ea0)', '01-check_access_ip_endpoint.t') called at /Users/username/perl5/lib/perl5/TAP/Harness.pm line 558
    TAP::Harness::__ANON__() called at /Users/username/perl5/lib/perl5/TAP/Harness.pm line 571
    TAP::Harness::runtests('Test::Rail::Harness=HASH(0x7fe2ecfd98d0)', '01-check_access_ip_endpoint.t') called at /Users/username/perl5/lib/perl5/App/Prove.pm line 546
    App::Prove::_runtests('App::Prove=HASH(0x7fe2ec005710)', 'HASH(0x7fe2ec23aca0)', '01-check_access_ip_endpoint.t') called at /Users/username/perl5/lib/perl5/App/Prove.pm line 504
    App::Prove::run('App::Prove=HASH(0x7fe2ec005710)') called at /Users/username/perl5/bin/prove line 12
# Failed!
# No Such test case in TestRail (26870622).
01-check_access_ip_endpoint.t .. ok   
All tests successful.
Files=1, Tests=2,  4 wallclock secs ( 0.33 usr  0.03 sys +  0.24 cusr  0.04 csys =  0.64 CPU)
Result: PASS
```

**Comment by troglodyne** [comment] 2016-10-25 22:12
Root cause is that LWP doesn't follow redirects by default on POST requests.

Whether "that's the module's problem" is debatable (do you *really* want to blithely accept POST request redirects, considering that it usually involves sending things like credentials over the wire?), but resolving it wouldn't be difficult, you'd just have to add 'POST' to the arrayref of LWP's requests_redirectable option.

**Comment by teodesian** [comment] 2016-10-25 23:09
Yeah, this is probably due to a certain testrail domain which used to legitimately resolve to both a .qa and .net TLD now only resolving to .net, but having a redirect for the .qa domain.  Should be fixable by changing your testrailrc to use the non-redirect domain (.net).

That said, I should at least add remarks about this, and make it a controllable flag in the constructor.

**Comment by cPMarco** [comment] 2016-10-26 14:29
I think it should be trying to use .net, since I changed the rc file:
```
$ grep url ~/.testrailrc 
apiurl=http://testrail.domain.net
```
Is there another place this is set?

**Closed** 2016-12-12 16:52 UTC
